# redeploys the static site after every push
permissions:
  contents: write
name: deploy-pages
on:
  push:
    branches: [ "main" ] # Or your primary branch
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions: # <--- This block must be here, indented under 'deploy:'
      contents: read   # Required to checkout the repository
      pages: write     # Required to push to the gh-pages branch (this is for peaceiris)

    steps:
      - uses: actions/checkout@v4

      - name: Build static site
        run: |
          mkdir public
          cp -r web/* public/
          cp -r data public/

      - name: List files in public directory
        run: ls -la public

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
