#redeploys the static site after every push

name: deploy-pages 
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write 

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: 
      name : github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    permissions:
      contents: read
      pages: write
      id-token: write 
    steps:
      - uses: actions/checkout@v4
      - name: Build static site
        run: |
          mkdir public
          cp -r web/* public/
          cp -r data public/
      - uses: actions/upload-pages-artifact@v3
        with: { path: public }
      - name: Debug ENV
        run: |
          echo "ID_TOKEN env: $ACTIONS_ID_TOKEN_REQUEST_URL"

      - uses: actions/deploy-pages@v4
