#redeploys the static site after every push

name: deploy-pages 
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build static site
        run: |
          mkdir public
          cp -r web/* public/
          cp -r data public/
      - uses: actions/upload-pages-artifact@v3
        with: { path: public }
      - uses: actions/deploy-pages@v4
